# Generated by Django 2.1 on 2019-02-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20190216_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
